# Data exploration and cleaning

inputs column

- raw email

expectations

- label/ground truth

In [1]:
import pandas as pd

df = pd.read_json('data/customer_service_emails.json')

df.head()

,input,expectations
0,{'email': 'From: Erik Lindqvist <erik.lindqvis...,"{'sender_name': 'Erik Lindqvist', 'sender_emai..."
1,{'email': 'From: Maja Bergström <maja.bergstro...,"{'sender_name': 'Maja Bergström', 'sender_emai..."
2,{'email': 'From: Oscar Johansson <oscar.johans...,"{'sender_name': 'Oscar Johansson', 'sender_ema..."
3,{'email': 'From: Linnea Karlsson <linnea.karls...,"{'sender_name': 'Linnea Karlsson', 'sender_ema..."

In [2]:
df.iloc[0]

input           {'email': 'From: Erik Lindqvist <erik.lindqvis...
expectations    {'sender_name': 'Erik Lindqvist', 'sender_emai...
Name: 0, dtype: object

In [3]:
print(df.iloc[0]['input']['email'])

From: Erik Lindqvist <erik.lindqvist@gmail.com>
Subject: Broken product received - Order #78901

Hello,

I am writing to express my deep disappointment with my recent purchase. I placed an order on your website last week and was quite excited to finally receive it. However, when the package arrived yesterday, I noticed that the box itself was already damaged, with visible dents and torn corners. I assumed it might just be the outer packaging, but unfortunately the product inside was also completely broken.

The item, which cost me 599 SEK, appears to have suffered significant damage during shipping. Several parts were cracked and one component was completely shattered. I took photos of both the packaging and the product immediately after opening the box.

I have been a loyal customer for over two years now and this is the first time I have experienced such an issue. I would appreciate either a full replacement sent to my address or a complete refund of the 599 SEK I paid. I also want to flag that the packaging may need improvement to prevent this from happening to other customers.

I look forward to your prompt response.

Best regards,
Erik Lindqvist
Customer since 2022

### Clean email json file
Format that MLFlow requires:

- input -> inputs
- {"expected_response": '{'sender_name': 'Erik Lindqvist', 'sender_emai...'}'

In [4]:
df = df.rename({'input': 'inputs'}, axis=1)

df

,inputs,expectations
0,{'email': 'From: Erik Lindqvist <erik.lindqvis...,"{'sender_name': 'Erik Lindqvist', 'sender_emai..."
1,{'email': 'From: Maja Bergström <maja.bergstro...,"{'sender_name': 'Maja Bergström', 'sender_emai..."
2,{'email': 'From: Oscar Johansson <oscar.johans...,"{'sender_name': 'Oscar Johansson', 'sender_ema..."
3,{'email': 'From: Linnea Karlsson <linnea.karls...,"{'sender_name': 'Linnea Karlsson', 'sender_ema..."

In [ ]:
df['expectations'].apply(lambda row: {'expected_response': row})

0    {'excepted_response': {'sender_name': 'Erik Li...
1    {'excepted_response': {'sender_name': 'Maja Be...
2    {'excepted_response': {'sender_name': 'Oscar J...
3    {'excepted_response': {'sender_name': 'Linnea ...
Name: expectations, dtype: object

In [6]:
import json
df['expectations'] = df['expectations'].apply(lambda row: {'excepted_response':json.dumps(row)})
df

,inputs,expectations
0,{'email': 'From: Erik Lindqvist <erik.lindqvis...,"{'excepted_response': '{""sender_name"": ""Erik L..."
1,{'email': 'From: Maja Bergström <maja.bergstro...,"{'excepted_response': '{""sender_name"": ""Maja B..."
2,{'email': 'From: Oscar Johansson <oscar.johans...,"{'excepted_response': '{""sender_name"": ""Oscar ..."
3,{'email': 'From: Linnea Karlsson <linnea.karls...,"{'excepted_response': '{""sender_name"": ""Linnea..."

In [ ]:
df.to_json('emails_cleaned.json', index=False, orient='records')  # Convert DataFrame to JSON file (list of records, no index)

In [8]:
pd.read_json("emails_cleaned.json").iloc[2]

inputs          {'email': 'From: Oscar Johansson <oscar.johans...
expectations    {'excepted_response': '{"sender_name": "Oscar ...
Name: 2, dtype: object